# Generated by Django 3.2.3 on 2021-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210519_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
